[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15.1.0"
floem = { git = "https://github.com/lapce/floem.git", rev = "9c88792baa76a196a0469da358b88764e8af5e6d" }
floem-text-editor = { path = "../.." }
